/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282219
 */
public class MedicoDialog extends javax.swing.JPanel {

    /**
     * Creates new form MedicoDialog
     */
    public MedicoDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cabecario = new javax.swing.JPanel();
        MedicoAdicionar = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(null);

        Cabecario.setBackground(new java.awt.Color(153, 153, 255));
        Cabecario.setLayout(null);

        MedicoAdicionar.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        MedicoAdicionar.setForeground(new java.awt.Color(0, 0, 0));
        MedicoAdicionar.setText("Médico - Adicionar");
        Cabecario.add(MedicoAdicionar);
        MedicoAdicionar.setBounds(110, 20, 270, 50);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/medico (1).png"))); // NOI18N
        Cabecario.add(Logo);
        Logo.setBounds(40, 30, 32, 30);

        add(Cabecario);
        Cabecario.setBounds(0, 0, 630, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do(a) médico(a): ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setLayout(null);

        Codigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Codigo.setText("Código:");
        jPanel2.add(Codigo);
        Codigo.setBounds(20, 40, 50, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 70, 100, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CRM:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, 50, 33, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(150, 70, 90, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome do(a) médico(a): ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 50, 150, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(270, 70, 330, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefone:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 110, 60, 20);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(20, 130, 150, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("E-mail:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 110, 50, 20);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(200, 130, 250, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Data de Nascimento:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(460, 110, 130, 20);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(460, 130, 130, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Lista de especialidades: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 170, 170, 20);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 150, 146);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/simbolo-de-setas-duplas-para-a-esquerda.png"))); // NOI18N
        jPanel2.add(jButton1);
        jButton1.setBounds(200, 200, 38, 39);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/simbolo-de-setas-duplas-para-a-direita-para-avancar.png"))); // NOI18N
        jPanel2.add(jButton2);
        jButton2.setBounds(200, 260, 40, 39);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Especialidades do médico: ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(270, 170, 180, 20);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(270, 190, 160, 146);

        add(jPanel2);
        jPanel2.setBounds(10, 100, 610, 360);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cancelar");
        add(jButton3);
        jButton3.setBounds(420, 470, 90, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Salvar");
        add(jButton4);
        jButton4.setBounds(520, 470, 90, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecario;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MedicoAdicionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
